language: python
env:
  global:
    - totalFrames=384
    - TotalJobsInPhase=10
  jobs:
    - JobPositionInPhase=1
    - JobPositionInPhase=2
    - JobPositionInPhase=3
    - JobPositionInPhase=4
    - JobPositionInPhase=5
    - JobPositionInPhase=6
    - JobPositionInPhase=7
    - JobPositionInPhase=8
    - JobPositionInPhase=9
    - JobPositionInPhase=10
before_install:
  - sudo snap install blender --classic
script:
  - ./render.sh test.blend