trigger:
  - master
  - tags

stages:
- stage: Render
  displayName: Render
  jobs:
  - job: linux_build_package
    displayName: Linux Build
    pool:
      vmImage: ubuntu-18.04
    workspace:
      clean: all
    strategy:
      parallel: 5 #
    variables:
      totalFrames: 50
    steps:
    - script: |
        sudo apt update
        sudo apt install snapd mesa-utils
      displayName: Install Dependencies
    #- script: |
    #    sudo add-apt-repository ppa:ubuntu-x-swat/updates
    #    sudo ACCEPT_EULA=Y apt-get update
    #    sudo ACCEPT_EULA=Y apt-get dist-upgrade
    #    glxinfo | grep "OpenGL version"
    #  displayName: Install mesa
    - script: |
        sudo snap install blender --classic
    - bash: |
        frames=$((totalFrames / $(System.TotalJobsInPhase)))
        offset=$(($(System.JobPositionInPhase) * ${frames}))
        frameend=$((${offset}+$frames))
        echo "rendering from ${offset} to ${frameend} total jobs $(System.TotalJobsInPhase) job id $(System.JobPositionInPhase)"
        #blender -b test.blend -a -s ${offset} -e ${frameend} -noaudio -o //output/render_#### -x 1
      displayName: Render
