trigger:
  - master
  - tags

stages:
- stage: Render
  displayName: Render
  jobs:
  - job: linux_build_package
    displayName: Linux Build
    pool:
      vmImage: ubuntu-18.04
    workspace:
      clean: all
    steps:
    - script: |
        sudo apt update
        sudo apt install snapd mesa-utils
      displayName: Install Dependencies
    - script: |
        sudo add-apt-repository ppa:ubuntu-x-swat/updates
        sudo apt-get update
        sudo apt-get dist-upgrade
        glxinfo | grep "OpenGL version"
      displayName: Install mesa
    - script: |
        sudo snap install blender --classic
    - script: |
        blender -b test.blend -a -noaudio -o //render.mp4
      displayName: Render
