# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildwindows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Get Blender
        run: curl -o blender.zip -L https://ftp.nluug.nl/pub/graphics/blender/release/Blender2.82/blender-2.82-windows64.zip
      - name: Extract some files
        run: 7z x blender.zip
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Render
        run: |
          copy opengl32.dll blender\blender-2.82-windows64\opengl32.dll
          blender\blender-2.82-windows64\blender.exe -b -d test.blend -noaudio -S Scene -E CYCLES -x 1 -F PNG -o ${{ github.workspace }}\frame_#### -s 0 -e 10 -a 
  buildmac:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  buildlinux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install snapd mesa-utils
          sudo snap install blender --classic
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Render
        run: blender -b test.blend -noaudio -S Scene -E CYCLES -x 1 -F PNG -o ${{ github.workspace }}/frame_#### -s 0 -e 10 -a
     
